[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
attention_market_protocol = "Ex4u9eFj65N9SQ1o5yCCCHuBuTPbhcnfEGi6W5tWuoq"

[programs.devnet]
attention_market_protocol = "Ex4u9eFj65N9SQ1o5yCCCHuBuTPbhcnfEGi6W5tWuoq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm run test:anchor"
